import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://master.dih.staging.sohohousedigital.com/');
  await page.getByRole('button', { name: 'Sign In' }).click();
  await page.getByRole('link', { name: 'sign in using your password' }).click();
  await page.locator('div').filter({ hasText: 'Email address' }).nth(2).click();
  await page.getByRole('textbox', { name: 'Email address' }).click();
  await page.getByRole('textbox', { name: 'Email address' }).fill('test_membershipcard@sohohouse.com');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('password');
//   await page.getByRole('textbox', { name: 'Password' }).press('Enter');
  await page.getByRole('button', { name: 'Continue' }).click();
//   await page.getByRole('button', { name: 'Reject' }).click();
//   await page.getByRole('button', { name: 'Join' }).click();
//   await expect(page.getByRole('navigation')).toMatchAriaSnapshot(`
//     - link "Join" [expanded]:
//       - /url: /membership
//     `);
  await page.getByRole('button', { name: 'Reject' }).click();
  await page.getByRole('link', { name: 'Join' }).click();
//   const page1Promise = page.waitForEvent('popup');
  await page.getByRole('link', { name: 'Apply for membership' }).first().click();
//   const page1 = await page1Promise;
  await page.goto('https://master.dih.staging.sohohousedigital.com/apply/01666c98-281a-4e47-ad74-3c756ccb6ea2/package');
  await page.getByRole('spinbutton').first().click();
  await page.getByRole('spinbutton').first().fill('12');
  await page.getByRole('spinbutton').nth(1).dblclick();
  await page.getByRole('spinbutton').nth(1).fill('10');
  await page.getByRole('spinbutton').nth(2).dblclick();
  await page.getByRole('spinbutton').nth(2).fill('2000');
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.getByRole('textbox', { name: 'Search address' }).dblclick();
  await page.getByRole('textbox', { name: 'Search address' }).dblclick();
  await page.getByRole('textbox', { name: 'Search address' }).dblclick();
  await page.getByRole('textbox', { name: 'Search address' }).dblclick();
  await page.locator('.ds__inputLabel').first().dblclick();
  await page.getByRole('textbox', { name: 'Search address' }).dblclick();
  await page.getByRole('textbox', { name: 'Search address' }).fill('5 KEIGHLEY CLOSE,, mk10 9wp, London, United Kingdom, GB, Buckinghamshire');
  await page.getByRole('textbox', { name: 'Search address' }).dblclick();
  await page.getByRole('textbox', { name: 'Search address' }).fill(', London, United Kingdom, GB, Buckinghamshire');
  await page.getByRole('textbox', { name: 'Search address' }).click();
  await page.getByRole('textbox', { name: 'Search address' }).fill(', Buckinghamshire');
//   await page.getByRole('textbox', { name: 'Search address' }).press('ArrowRight');
//   await page.getByRole('textbox', { name: 'Search address' }).press('ArrowRight');
//   await page.getByRole('textbox', { name: 'Search address' }).press('ArrowRight');
//   await page.getByRole('textbox', { name: 'Search address' }).press('ArrowRight');
//   await page.getByRole('textbox', { name: 'Search address' }).press('ArrowRight');
//   await page.getByRole('textbox', { name: 'Search address' }).press('ArrowRight');
//   await page.getByRole('textbox', { name: 'Search address' }).press('ArrowRight');
//   await page.getByRole('textbox', { name: 'Search address' }).press('ArrowRight');
//   await page.getByRole('textbox', { name: 'Search address' }).press('ArrowRight');
//   await page.getByRole('textbox', { name: 'Search address' }).press('ArrowRight');
//   await page.getByRole('textbox', { name: 'Search address' }).press('ArrowRight');
//   await page.getByRole('textbox', { name: 'Search address' }).press('ArrowRight');
//   await page.getByRole('textbox', { name: 'Search address' }).press('ArrowRight');
//   await page.getByRole('textbox', { name: 'Search address' }).press('ArrowRight');
//   await page.getByRole('textbox', { name: 'Search address' }).press('ArrowRight');
//   await page.getByRole('textbox', { name: 'Search address' }).press('ArrowRight');
//   await page.getByRole('textbox', { name: 'Search address' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Search address' }).fill('95 Harley St, London, Greater London W1G 9QY, UK');
  await page.getByRole('textbox', { name: 'Search address' }).press('Enter');
  await page.getByRole('menuitem', { name: 'multi-select-item--95 Harley' }).click();
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.getByRole('button', { name: 'Select location 180 House' }).click();
  await page.getByText('UK').nth(1).click();
  await page.getByRole('menuitem', { name: 'radio-menu-item--180 House' }).click();
  await page.getByRole('button', { name: 'Confirm selection' }).click();
  await page.getByRole('button', { name: 'Continue' }).click();
//   await page.waitForTimeout(10000); 
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.waitForTimeout(4000); 
// await expect(page.getByText('Your profile')).toBeVisible();
 await page.getByRole("heading", { name: "Your profile" }).waitFor({ state: "visible" });
  await page.getByRole('textbox', { name: 'Mobile number' }).click();
  await page.getByRole('textbox', { name: 'Mobile number' }).fill('07752 593813');
  await page.getByText('Update photo').first().click();
  await page.locator('#headshot').setInputFiles('tests/testData/facephoto.png');
  await page.locator('form').getByText('Update photo').click();
  await page.locator('#identification').setInputFiles('tests/testData/valid_PhotoID.jpg');
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.waitForTimeout(3000); 
// await expect(page.getByText('Where do you work')).toBeVisible();
// await expect(page.getByText(/where do you work/i)).toBeVisible();
  await page.getByRole('textbox', { name: 'Where do you work' }).click();
  await page.getByRole('textbox', { name: 'Where do you work' }).fill('testing 1');
  await page.getByLabel('Type of work').selectOption('Art');
  await page.getByLabel('Role').selectOption('Account coordinator');
  await page.getByRole('textbox', { name: 'Work email' }).click();
  await page.getByRole('textbox', { name: 'Work email' }).fill('divya.rao@sohohousedigital.com');
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.waitForTimeout(3000); 
//   await page.getByLabel('', { exact: true }).click();
//   await page.getByLabel('', { exact: true }).fill('testing.  hippkpsb rnicoirn sot vmsorgcsrcfj ijoj4 dx234');
//   await page.getByRole('button', { name: 'Continue' }).click();
//   await page.locator('.ds__toggle__input').click();
//   await page.getByRole('button', { name: 'Continue' }).click();
//   await page.waitForTimeout(2000); 
// //   await page.getByRole('button', { name: 'Continue' }).click();
//   await page.locator('form div').filter({ hasText: 'Choose your payment term' }).nth(1).click();
});